CREATE IF NOT EXISTS TABLE NODE(
  ID INT PRIMARY KEY,
  ACCOUNT VARCHAR(50) NOT NULL,
  DOMAIND VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  PARENT INT,
  FOREIGN KEY (PARENT) REFERENCES NODE(ID) ON DELETE CASCADE
);